# fly.toml app configuration file generated for mds-moderator on 2024-07-17T07:48:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mds-moderator'
primary_region = 'fra'

[build]

[env]
  FLY_APP_NAME = 'mds-moderator'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512'
  cpu_kind = 'shared'
  cpus = 1
